name: 'portfolio'
config-version: 2

profile: 'portfolio'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  portfolio:
    shared:
      +materialized: view
      +schema: shared
    staging:
      toronto:
        +materialized: view
        +schema: stg_toronto
      football:
        +materialized: view
        +schema: stg_football
    intermediate:
      toronto:
        +materialized: view
        +schema: int_toronto
      football:
        +materialized: view
        +schema: int_football
    marts:
      toronto:
        +materialized: table
        +schema: mart_toronto
      football:
        +materialized: table
        +schema: mart_football
