name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            set -euo pipefail

            cd ~/apps/personal-portfolio-dataflow

            echo "Pulling latest changes..."
            git fetch origin staging
            git reset --hard origin/staging

            echo "Activating virtual environment..."
            source .venv/bin/activate

            echo "Installing dependencies..."
            pip install -e ".[dev,dbt]" --quiet

            echo "Starting PostgreSQL if not running..."
            docker compose up -d postgres

            echo "Waiting for database..."
            sleep 5

            echo "Loading environment variables..."
            set -a && source .env && set +a

            echo "Applying schema migrations..."
            python scripts/db/init_schema.py

            echo "Running dbt models..."
            cd dbt && dbt run --profiles-dir . && cd ..

            echo "Running dbt tests..."
            cd dbt && dbt test --profiles-dir . && cd ..

            echo "Staging deployment complete!"
