name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -euo pipefail

            cd ~/apps/portfolio-dataflow

            echo "Pulling latest changes..."
            git fetch origin main
            git reset --hard origin/main

            echo "Activating virtual environment..."
            source .venv/bin/activate

            echo "Installing dependencies..."
            pip install -e ".[dev,dbt]" --quiet

            echo "Verifying PostgreSQL connection..."
            docker compose ps postgres

            echo "Running dbt models..."
            cd dbt && dbt run --profiles-dir . && cd ..

            echo "Running dbt tests..."
            cd dbt && dbt test --profiles-dir . && cd ..

            echo "Production deployment complete!"
